services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/tmp/data

  web:
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    env_file:
      - env.list
    depends_on:
      - cache

volumes:
  cache:
    driver: local
